### ISSUE TITLE
Multiple service instances of a type bound to one application

### ISSUE THREAD

**Issue by gfoster1** [pivotal-cf/java-cfenv#78] opened 2019-11-14 18:04 UTC
I am trying to figure out how to process the case where I have multiple service instances bound to an application and I am unsure if the current process handles this case. For example, assume I have multiple database instance bound to a class and I want to implement some sort of post processing on one database instance but not the other then there is no current way to implement this unless the implementing CfEnvProcessor maintains some sort of state of the instance name. Another example of this would be the case if I want to inject failover connections or have some multi region support for one application.

**Comment by dyroberts** [comment] 2020-03-18 14:27
Duplicate of #87

**Closed by dyroberts** 2020-03-18 14:27 UTC
